### ISSUE TITLE
Abililty to load/convert a YAML file containing multiple documents

### ISSUE THREAD

**Issue by ukch** [twardoch/yaplon#6]
Example YAML file:
```yaml
---
name: document1
---
name: document2
...
```

Running the command `yaplon y2j -i example.yaml` gives me the following:
```
Traceback (most recent call last):
  File ".../bin/yaplon", line 8, in <module>
    sys.exit(cli())
  File ".../lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File ".../lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".../lib/python3.8/site-packages/yaplon/__main__.py", line 232, in yaml2json
    obj = oyaml.read_yaml(input)
  File ".../lib/python3.8/site-packages/yaplon/oyaml.py", line 100, in read_yaml
    return yaml.load(stream, Loader)
  File ".../lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File ".../lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File ".../lib/python3.8/site-packages/yaml/composer.py", line 41, in get_single_node
    raise ComposerError("expected a single document in the stream",
yaml.composer.ComposerError: expected a single document in the stream
  in "example.yaml", line 2, column 1
but found another document
  in "example.yaml", line 3, column 1
```

The underlying YAML library has a `load_all` function, which could be used in these cases. Obviously a JSON file can only store a single document, so perhaps in this case you would need some way of providing multiple output filenames or choosing which of the YAML documents in the file is the one you're actually interested in.

**Comment by twardoch** [comment]
I think this is better left for some other utility that inlines the YAML files.
